Update step architecture
bitrise-steplib/steps-go-test pull request #11
Opened 2022-11-10 18:35 UTC by Grayson

### Checklist
- [ x ] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [ x ] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)

### Context

Arguably, this change isn't immediately necessary.  However, this attempts to do three things that may be useful for maintenance purposes:

1. Refactors the code into a better architecture.
2. Migrates dependencies to newer versions.
3. Adds some integration and unit tests around the most important parts of the code.

In addition, the Readme has been updated and the workflows have been reconsidered to make better use of preferred tooling.

### Changes

* Moves step to modern Go module format
* Updates step in a way that separates concerns and improves architecture
* Adds integration tests around file system interactions
* Adds unit tests around core code paths
* Updates to v2 versions of Bitrise packages
* Fixes various linter issues
* Updates workflows to use preferred tools
* Update ReadMe to recent format

2022-11-10 21:14 UTC, vshah23 requested changes
Added a few nitpicking comments.

2022-11-11 00:38 UTC, Grayson commented on step/step.go
> +	s.logger.Infof("\nRunning go test...")
Thanks!  What's the rationale around this?  Just to get another newline in and make it look nicer or is there something that I'm not anticipating?

2022-11-11 00:39 UTC, Grayson commented on step/step.go
> +type envvars struct {
No objection... but should it be exported?  I don't think it'll be used anywhere else.  `inputs`?

2022-11-15 13:16 UTC, vshah23 commented on step/step.go
> +type envvars struct {
I don't think it needs to be, but I have only seen examples where it is exported. I'm good with leaving it unexported unless it need to be used elsewhere!

2022-11-15 13:16 UTC, vshah23 commented on step/step.go
> +	s.logger.Infof("\nRunning go test...")
Yes, just to get another newline in and make it look nicer.

2022-11-15 14:57 UTC, Grayson commented on step/step.go
> +	s.logger.Infof("\nRunning go test...")
Taking another look, it seems like we were trying to do that with the `\n` prior to the caption.  That feels easy to miss, so I might remove that and put in the `Println()` unless we actually need both.

2025-02-05 13:28 UTC, godrei commented
Hi @Grayson, I'm sorry for being late with this PR. In the meantime, [we've modernized the Step](https://github.com/bitrise-steplib/steps-go-test/pull/13), so this change has become obsolete. I'm closing this PR now.

2025-02-05 13:28 UTC, closed without merging

2025-02-11 18:33 UTC, Grayson commented
Oh no!  My heart is broken! :P

I like the new modernized Step!  Keep up the good work.  Thanks for closing this out.  I miss y'all!